                                        Assignment                                                       
                                         Module 3                                                             
                                     NumPy for AI/ML                                                         
name: Uppaluru Renu Chowadry

rollno: 238T1A12C0

Batch:2

### **Section A - Conceptual Understanding**



A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads?      Mention at least two concrete reasons. 

ans:  
      1. They are faster for numerical calculations due to optimized operation. 
      2. They use less memory and support efficient operations on large datasets.


A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

ans:  
       ->Vectorization means performing an operation on an entire Numpy array at once instead of using a python for loop.
       ->It matters for large datasets because Numpy performs these operations using optimized low-level code makeing calculation much faster than explicit python loops.


A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

ans: 
         -> A * B performs element-wise multiplication.
         example: multiplying an input/activation array by a mask or scaling values.
          -> A @ B performs matrix multiplication.
         example: multiplying input features by a layer's weight matrix.


A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise. 

ans:  
          Broadcasting:
                  is Numpy way of performing element-wise operation on arrays with different but compatible shapes.
      General rule-
                   Starting from the last dimension, the dimensions must either
                    ->Equal.
                    ->One of them must be 1.
if these conditions are nit satisfied the arrays cannot be broadcast together.


A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

ans:  
          flatten() always returns a new copy of the array.
          ravel() returns a flattened view whenever possinle so it generally uses less memory.

          ->for a memory constrained application processing large images, i would prefer ravel() because it can avoid creating an unnecessary copy and therefore saves memory.


A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example. 

ans:

for 2D array:
        -> axis=0 performs the operation column-wise.
        -> axis=1 performs the operation row-wise. 

In [1]:
import numpy as np
a = np.array([[1,2],
            [3,4]]) 
print(np.sum(a, axis=0))   
print(np.sum(a, axis=1))

[4 6]
[3 7]


A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

Ans:
    ->Scaling features helps ML models learn faster and prevents features with large values from dominating the model.
    ->Normalization: Converts values to a fixed range, usually 0 to 1.
    ->Standardization: Converts values so they have mean = 0 and standard deviation=1.

A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? 

Ans:  
     ->np.nanmean() calculates the mean while ignoring NaN (missing) values.
     ->np.mean() does not ignore NaN values. If the data contains NaN, the result will usually be NaN.

In [27]:
data=np.array([10,20,np.nan,40])
print(np.mean(data))
print(np.nanmean(data))

nan
23.333333333333332


A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.
        
Ans:
    In normal ML data, X.shape = (samples, features) represents the number of samples and features. For image data, we also include the height, width, and color channels. An RGB image has 3 channels: Red, Green, and Blue. Therefore, a batch of 64 RGB images, each of size 128 × 128, has the shape (64, 128, 128, 3). Here, 64 = number of images, 128 = height, 128 = width, and 3 = RGB channels.


A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed).

Ans:
    Reproducibility means getting the same results when an experiment is repeated.
    ML uses randomness in activities such as data splitting, initialization, and sampling. Fixing a random seed makes these random operations consistent.

### Section B – Predict the Output


B1. Predict the exact output and/or resulting shape. Justify in one sentence. 
ans: 
 Predicted Output:(3, 3)

Explanation:

Broadcasting the shape(3,) and (3,1) produces a (3, 3) result.

The 1D array is broadcast across the rows of the 2D array

In [2]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)


(3, 3)


B2. Predict the output and/or shape.

Predicted Output: [2 5]

Explanation: The Expression x[:, 1] select the all rows and index 1 and select the second column.

In [3]:
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

[2 5]


B3. Predict the output and/or shape.

Predicted Output: [10 20]

Explanation: The Boolean Condition arr % 10 == 0 check all the elements and returns the element that are divisible by 10.

In [4]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

[10 20]


B4. Predict the output and/or shape.

Predicted Output: [[10 14]
                   [14 20]]

Explanation:m.T @ m ,m.T-> Transpose of matrix m (rows become columns and columns become rows) m-> performs the matrix multiplication 
So,m.T @ m means multiplying the transpose of m with the original m.

In [5]:
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)

[[10 14]
 [14 20]]


B5. Predict the output and/or shape.

Predicted Output: nan 2.3333333333333335

Explanation: Calculate the average of all elements.Since the array contains NaN, the result is nan.Calculate the average and ignore the NaN values(missing values).

In [6]:
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

nan 2.3333333333333335


B6. Predict the output and/or shape.
Predicted Output: [0 1 1]
Explanation: np.where() checks each element if x>15 is true and returns the value is 1 otherwise if x>15 is false and returns the value is 0.

In [7]:
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

[0 1 1]


B7. Predict the output and/or shape.
Predicted Output: 2 12

ans:
     Create an array with 3 rows and 4 columns filled with zeros.
     ->ndim : Gives the number of dimensions -> 2
     ->a.size : Gives the total number of elements -> 3 * 4 = 12

In [8]:
a = np.zeros((3, 4))
print(a.ndim, a.size)

2 12


 B8. Predict the output and/or shape.

Predicted Output: [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

ans: [::-1, ::-1] reverse  both rows and columns.

In [9]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### Section C – Coding / Implementation


C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 

ans:
    np.where(), where score greater than or equal to 40 is to print the "P" and where score below to print the "F".

In [23]:
import numpy as np
scores =np.array([35, 45, 60,28, 75])
result = np.where(scores >=40, 'P' , 'F')
print(scores)
print(result)

[35 45 60 28 75]
['F' 'P' 'P' 'F' 'P']


C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.

ans:
     The function standardizes each value using the z-score formula (x-mean)/std.

In [24]:
import numpy as np

def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

x = np.array([10, 20, 30, 40, 50])
print("Original:",x)
print("Standardized:",standardize(x))

Original: [10 20 30 40 50]
Standardized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.

ans:

     np.vstack() combines the arrays vertically (row-wise). Since both batches have the same number of features (3 columns), vstack() is appropriate.

In [ ]:
batch1=np.array([[1,2,3],
                 [4,5,6]])
batch2=np.array([[7,8,9,],
                 [10,11,12]])
combined=np.vstack((batch1,batch2))
print("Combined Array:")
print(combined)
print("Resulting Shape",combined.shape)

Combined Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Resulting Shape (4, 3)


C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

ans:
     axis=0 calculates statistics for each feature column, and broadcasting applies the column-wise mean and standard deviation to all rows.

In [26]:
import numpy as np
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std
print("Original shape",X.shape)
print("Standardized Shape:",X_standardized.shape)

Original shape (3, 2)
Standardized Shape: (3, 2)


C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true.

ans: 
       X: feature matrix of shape (n_samples, n_features),w: weight vector of shape(n_features),b: bias (scalar),y_true: actual target values

In [12]:
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])
w = np.array([0.5, 1.0])
b = 2
y_true = np.array([4, 7, 10])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [ 4.5  7.5 10.5]
MSE: 0.25


C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.

ans: 
     The fixed seed 42 ensures that the same random numbers are generated each time.


In [19]:
import numpy as np
rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10,3))
rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10,3))
print(data1.shape)
print(np.array_equal(data1, data2))

(10, 3)
True


C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization. 

ans:
    -> The min-max formula is:

normalized = (x - min(x)) / (max(x) - min(x))
    -> image.max() == image.min(), so the denominator is zero; that case should be handled separately.

In [ ]:
import numpy as np

image = np.array([[0, 50, 100],
                  [150, 200, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)
print("Minimum:", normalized.min())
print("Maximum:", normalized.max())

[[0.         0.50196078 1.        ]
 [0.19607843 0.39215686 0.78431373]]
Minimum: 0.0
Maximum: 1.0


C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

ans:
     We want one average value per image, so we average over height, width, and channels: axis=(1, 2, 3). We leave axis=0 untouched because it identifies the individual images.

In [22]:
import numpy as np
images = np.random.default_rng(42).integers(0, 256, size=(4, 28, 28, 3))
average_values = images.mean(axis=(1,2,3))
print("Average Value:",average_values)
print("Average shape value:",average_values.shape)

Average Value: [127.56505102 126.25212585 125.75722789 126.9914966 ]
Average shape value: (4,)


### Section D – Applied / Scenario-Based Problems


### D1. Data Preprocessing Pipeline 

You are given a raw 1D or 2D NumPy array containing NaN values.
Describe, step by step, the NumPy operations you would apply to:
(a) detect missing values,
(b) handle them appropriately and justify your strategy, and
(c) normalize or standardize the clean data before it is fed to a model.

ans:
     Data Preprocessing Pipeline:
                                 When working with real-world data, missing values can occur and are commonly represented by NaN in NumPy. Before feeding the data into a machine learning model, these missing values should be detected and handled properly so that they do not cause incorrect calculations or affect model training.

step-by-step:

Step 1 - Detect missing values:
                      
         I would use np.isnan() to identify which elements of the array contain NaN values. It returns a Boolean array where True indicates a missing value and False indicates a valid value. I can also use np.isnan(data).sum() to find the total number of missing values.

Step 2 - Handle missing values:

         After detecting the missing values, I would replace them with appropriate values instead of directly passing them to the model. For numerical data, replacing a missing value with the mean of its feature is one possible strategy. I would use np.nanmean() to calculate the mean while ignoring existing NaN values. This approach allows us to retain the available samples instead of removing complete rows.

For this example, I will use column-wise mean imputation because the data is 2D and each column represents a numerical feature. This keeps the replacement value specific to each feature.

Step 3 - Verify the cleaned data:

         After replacing the NaN values, I would check the array again using np.isnan() to make sure that no missing values remain. This is important before performing further preprocessing.

Step 4 - Standardize the clean data:

        Once the missing values have been handled, I would standardize the numerical features. Standardization subtracts the mean of each feature and divides by its standard deviation. The resulting features have approximately mean 0 and standard deviation 1. This can help machine learning models when the features have different scales.

The standardization formula is:

          standardized_data = (data - mean) / standard_deviation

I would calculate the mean and standard deviation column-wise using axis=0. NumPy broadcasting then applies these values to every row without requiring an explicit Python loop.

In [28]:
data = np.array([ [10.0, 20.0], 
    [15.0, np.nan], 
    [20.0, 40.0], 
    [25.0, 50.0]
]) 

print("Missing values:") 
print(np.isnan(data)) 

column_mean = np.nanmean(data, axis=0) 

clean_data = np.where( np.isnan(data), column_mean, data ) 
 
mean = clean_data.mean(axis=0) 
std = clean_data.std(axis=0) 

standardized_data = (clean_data - mean) / std 
print("Clean data:") 
print(clean_data)
print("Standardized data:") 
print(standardized_data)

Missing values:
[[False False]
 [False  True]
 [False False]
 [False False]]
Clean data:
[[10.         20.        ]
 [15.         36.66666667]
 [20.         40.        ]
 [25.         50.        ]]
Standardized data:
[[-1.34164079 -1.5430335 ]
 [-0.4472136   0.        ]
 [ 0.4472136   0.3086067 ]
 [ 1.34164079  1.2344268 ]]


### D2. Image Batch Understanding

1. Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

ans:
 
   A single RGB image with a height and width of 64 * 64 has three color channels: Red, Green, and Blue. Therefore, its NumPy shape is (64, 64, 3), where the three dimensions represent height, width, and color channels.

   When multiple RGB images are stored together as a batch, an additional dimension is added at the beginning to represent the number of images. Therefore, a batch of 16 RGB images has the shape (16, 64, 64, 3).

   Here, 16 represents the number of images, 64 * 64 represents the height and width of each image, and 3 represents the RGB channels.

2. Write code to create a dummy batch of 16 images of size 64 * 64 using random pixel values.

ans:

    The following code creates a batch of 16 RGB images with dimensions 64 * 64. Each pixel is represented using three channels: Red, Green, and Blue.

In [29]:
import numpy as np

rng = np.random.default_rng(42)

images = rng.integers(
    0, 256,
    size=(16, 64, 64, 3)
)

print(images.shape)

(16, 64, 64, 3)


3. Compute the average image of the batch, meaning the element-wise mean across all 16 images.

In [30]:
average_image = images.mean(axis=0) 
print(average_image.shape)

(64, 64, 3)


4. State the shape of your result and explain why.

ans:
    The resulting average image has the shape (64, 64, 3). This is because axis=0 represents the 16 images in the batch, 
    so taking the mean along this axis calculates the average pixel value at each corresponding position across all 16 images.
    The height, width, and RGB channel dimensions are not reduced, so they remain (64, 64, 3). 
    In other words, the operation converts 16 separate images into one average RGB image while preserving the original image dimensions

### D3. Debug the Model Code

Bug 1: 
      Weight vector shape
      X has shape (3, 2), which means there are 3 samples and 2 features. Therefore, the weight vector must contain 2 values and have shape (2,).

The original w has shape (3,). This makes X @ w invalid because matrix multiplication would require (3, 2) @ (2,), but the code attempts (3, 2) @ (3,).

Bug 2:
      Incorrect MSE calculation
The original expression is:

np.mean(y_true - y_pred ** 2)

Because exponentiation has higher precedence than subtraction, Python evaluates this as:

np.mean(y_true - (y_pred ** 2))

For Mean Squared Error, the difference must be calculated first and then squared. Therefore, the correct expression is:

np.mean((y_true - y_pred) ** 2)

In [31]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("y_pred =", y_pred)
print("MSE =", mse)

y_pred = [4.5 6.  7.5]
MSE = 244.16666666666666


### Section E - Bonus / Challenge

E1. Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.

ans:

Min-max normalization scales each feature to a range between 0 and 1. Since this question requires per-column normalization, the minimum and maximum values are calculated separately for each feature column using axis=0.

The normalization formula is:

(X - column_min) / (column_max - column_min)

NumPy broadcasting automatically applies each column's minimum and maximum to the corresponding column. Therefore, the entire operation is vectorized and does not require explicit loops over rows or columns.

In [32]:
X = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
    [30, 300, 3000],
    [40, 400, 4000]
])
# Finding the minimum and maximum for each column
column_min = X.min(axis=0)
column_max = X.max(axis=0)
# Per-column min-max normalization
X_normalized = (X - column_min) / (column_max - column_min)
print("Original matrix:")
print(X)
print("\nColumn minimums:")
print(column_min)
print("\nColumn maximums:")
print(column_max)
print("\nNormalized matrix:")
print(X_normalized)

Original matrix:
[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]
 [  40  400 4000]]

Column minimums:
[  10  100 1000]

Column maximums:
[  40  400 4000]

Normalized matrix:
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


E2. Three-Level Score Classification 
Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).
Hint: You may need to nest or combine np.where() calls.

ans:
   The exam scores need to be classified into three categories based on their values. Scores below 40 are classified as "Fail", scores from 40 to 70 inclusive are classified as "Average", and scores above 70 are classified as "Excellent".

   I use nested np.where() to perform all three classifications in a single vectorized expression. The first np.where() checks whether a score is below 40. If it is not, the second np.where() checks whether the score is less than or equal to 70. This avoids explicit loops and if/else statements.

code explanetion:
          ->The outer np.where() checks whether each score is less than 40 and assigns "Fail" when the condition is true. For the remaining scores, 
          ->The inner np.where() checks whether the score is less than or equal to 70 and assigns "Average"; otherwise it assigns "Excellent".
          ->The entire classification is performed using one vectorized expression, so no explicit Python loops or if/else statements are required.

In [33]:
import numpy as np 
scores = np.array([25, 40, 55, 70, 71, 90]) 
result = np.where(
     scores < 40,
      'Fail', 
np.where(scores <= 70, 'Average', 'Excellent') )
print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


                                       ## End of the Assignment-3                                                 